### ISSUE TITLE
dlg-no-drag issue with x and y

### ISSUE THREAD

**Issue by ray73864** [keejelo/EasyDialogBox#2]
Noticed that if I set the dialog to 'dlg-no-drag', it gets stuck permanently in the upper left corner with no way to move it.

If I remove the 'dlg-no-drag', then it obeys the 'x' and 'y' that I have set for it.

**Comment by keejelo** [comment]
Hi, I'll check it out and try to fix this.

**Comment by keejelo** [comment]
I think I have solved this issue now, did some changes to the file "easydlg.css"
try latest update from the repository.

**Comment by ray73864** [comment]
Latest update fixes this perfectly :D

**Comment by keejelo** [comment]
That's great to hear :)
