### ISSUE TITLE
Dialog events support

### ISSUE THREAD

**Issue by ray73864** [keejelo/EasyDialogBox#3]
Wondering if there is the possibility of events for the dialog, for when the dialog is being added to the DOM, has been added to the DOM but not yet shown, has been shown, and similarly for the closing of the dialog.

I'm trying to create a multi-input dialog box and need to be able to attach event listeners to the inputs on the dialog so that when a user presses the enter key, it goes to the next input box, when I was using Bootstraps dialogs (before I got rid of jQuery completely), I was doing it in the .on("show.bs.modal") event, but I can't quite work out how to do it in this one.

**Comment by keejelo** [comment]
Hi, yes I'll try to implement those events.

**Comment by keejelo** [comment]
Added some event-functions now, testing it seems to work ok!

myObj.onCreate() ....... fires when dialog is created and added to DOM
myObj.onShow() ......... fires when dialog is about to be displayed
myObj.onClose() ......... fires when dialog is closing

You can try it out and see if you can work with it!
Use latest update of repos. file: "easydlg.js"
:)

**Comment by keejelo** [comment]
@ray73864 
Did it work for you ?
Can this issue be closed ?

**Comment by ray73864** [comment]
Sorry, been a bit busy at work, will check later on this week for you.

**Comment by keejelo** [comment]
Ok, no worries, no stress 👍🙂
