### ISSUE TITLE
Display problem with header and footer

### ISSUE THREAD

**Issue by ray73864** [keejelo/EasyDialogBox#4]
The header and footer are being cut off when I try and use the examples on my internal website, I'm using Bootstrap 4 for the site.

https://puu.sh/GiLL9/4cd2ea2d18.png

When I look in the dev tools (Using Microsoft Edge Chromium v84.0.522.59) it is missing the '20px' height for both.

I copied and pasted the javascript demo from the webpage, when I run the example on the EasyDialogBox webpage it shows fine.

I did have to add 'charset="UTF-8"' to both the stylesheet link and the script src, otherwise I wouldn't get the 'X' in the right hand side of the header, but I haven't been able to figure out what is causing the dialog to not show properly.

**Comment by keejelo** [comment]
Hi, what kind of doctype are you using?
The example is using HTML5 doctype.  `<!doctype html>`
try it and see if it helps.
I'll try to look into this issue and see if I can reproduce the same display error as you.

**Comment by ray73864** [comment]
Hi, <!doctype html> is what I use already.

**Comment by keejelo** [comment]
It seems to have something to do with bootstraps css
I'm going to investigate further and see if I can fix it.

**Comment by keejelo** [comment]
Think I fixed the problem.
I created a custom css file to use when using Bootstrap 4.
I tried it and it seems to get rid of the header and footer "cut-off".
Try to use the file "easydlg_bootstrap.css" instead of regular file "easydlg.css" and see if it works for you.
:)

**Comment by keejelo** [comment]
@ray73864 
Did it work for you?
Can this issue be closed ?
