### ISSUE TITLE
Escape key to close dialog

### ISSUE THREAD

**Issue by ray73864** [keejelo/EasyDialogBox#5]
Any chance of getting it so that the escape key can close the dialog?

**Comment by keejelo** [comment]
Hi, yes I can add that, I'll do it.

**Comment by keejelo** [comment]
"Escape key to close dialog" is now added.
Try the latest update of file "easydlg.js" from the repos.
:)

**Comment by keejelo** [comment]
This issue seem to be resolved, so I'm closing it.
