### ISSUE TITLE
Add DOM element to returned dialog

### ISSUE THREAD

**Issue by ray73864** [keejelo/EasyDialogBox#7]
Wasn't really sure how to word this one, it's really more a quality of life type thing than anything else.

Basically when you do

```
let myDialog = EasyDialogBox.create(null, "dlg", "my title", "my dialog", fnCallback);
```

The returned object should have the newly created DOM element included in it (for example: myDialog.el, or myDialog.element, etc...).

That way you don't have to do ```document.querySelector(myDialog.id);```

I mean, doing that is easy enough, but it does mean a search of the DOM tree to find it, where as the 'create' function already knows about the DOM element.

**Comment by keejelo** [comment]
<strike>I think I maybe understand what you mean..
All created elements within the dialog should automatically become an object variable ?
I'll look into it, might not be so hard to get it done.

Think it might be similar to doing this, but to automate it when creating the dialog:
```
let myFormElements = document.getElementById('myDialogForm').childNodes;
myFormElements[0];  // element 0
myFormElements[1];  // element 1
myFormElements[2];  // element 2
myFormElements[3];  // element 3
// and so on..

// then you could get the element by index and do stuff with it's properties:
myFormElements[0].value = 'hello';

// and more.. 
```
</strike>

**Comment by keejelo** [comment]
<strike>I'll automate this and make it so form elements values are saved on "hiding"  https://github.com/keejelo/EasyDialogBox/issues/6#issuecomment-796484617</strike>

**Comment by keejelo** [comment]
<strike>Made a new test version, wrote about it in the other issue:
https://github.com/keejelo/EasyDialogBox/issues/6#issuecomment-798771114

Update:
This is now possible in the new test version:
https://github.com/keejelo/EasyDialogBox/tree/master/js/test</strike>

**Comment by keejelo** [comment]
New release ready.
The create function now returns reference to the DOM element, element added to returned dialog.
You can get it by doing: <code>myObj.el;</code>
additional you can get the elements inside dialog:
<pre>
myObj.$();              // using () blank, returns the dialogbox HTML element itself
myObj.$('#someID');     // using # (hash), returns the HTML element containing the specified ID
myObj.$('.someClass');  // using . (dot), returns an indexed HTMLCollection ([i] as normal)
myObj.$('someElement'); // returns an indexed HTMLCollection ([i] as normal)
or mix it up
..similar to .querySelectorAll()
</pre>
And the "bKeepAlive" parameter is removed from the create function, so don't use it.
Usage is now:
<code>let myObj = EasyDialogBox.create(id, strBoxTypeClass, strTitle, strMessage, fnCallback, x, y, w, h);</code>
where of course the parameter "fnCallback" is optional, use 0 (zero) if not using it.
At minimum you can use: 
<code>let myObj = EasyDialogBox.create(id, strBoxTypeClass, strTitle, strMessage);</code>
and skipping the last paramters.
:)

**Comment by ray73864** [comment]
Working perfectly :D

**Comment by ray73864** [comment]
This doesn't seem to be happening anymore on the latest version.

myBox.el returns 'null' instead of the element.

I can still retrieve the element via myBox.$() however.

**Comment by keejelo** [comment]
Ok, I'll check it out, sorry.

**Comment by keejelo** [comment]
Fixed it now, I had commented out a line in the code, should work ok now.
Try the latest file "easydlg.js"
